import { ThemeProvider } from "@mui/material"; // Import MUI components
import type { Metadata } from "next";
import "./globals.css";
import theme from "@/theme"; // Ensure this path is correct
import { geistMono, geistSans } from "@/utils/helper";
import ReactQueryProvider from "@/utils/providers/ReactQueryProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
      <ReactQueryProvider>
        <ThemeProvider theme={theme}>
         {children}
        </ThemeProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
